[package]
name = "aster-exfat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aster-nix = { path = "../../../kernel" }
aster-block = { path = "../../../kernel/comps/block"}
aster-rights = { path = "../../../kernel/libs/aster-rights" }
ostd = { path = "../../../ostd" }
align_ext = { path = "../../../ostd/libs/align_ext" }
component = { path = "../../../kernel/libs/comp-sys/component" }

bitvec = { version = "1.0.1", default-features = false, features = ["alloc"] }
time = { version = "0.3", default-features = false, features = ["alloc"] }

log = "0.4"
lru = "0.12.3"
hashbrown = "0.14"
bitflags = "1.3.2"
ctor = { git="https://github.com/asterinas/rust-ctor" }

[lints]
workspace = true
